### ISSUE TITLE
How to enable debug logging

### ISSUE THREAD

**Issue by mnach** [tmc/grpc-websocket-proxy#17]
I use etcd 3.3.15 which has this module compiled in.
I set --debug=true option to enable debug messages, but I don't see messages from this module in log file. 
So, how can I enable it?

**Comment by juwell** [comment]
did you add the param `wsproxy.WithLogger()` when you called `wsproxy.WebsocketProxy()`?
like this:
wsproxy.WebsocketProxy(mux, wsproxy.WithLogger(&WsProxyLog))

**Comment by mnach** [comment]
thanks! `etcd` doesn't called `WithLogger`
