### ISSUE TITLE
Support non-streaming grpc endpoints

### ISSUE THREAD

**Issue by nirshirion** [tmc/grpc-websocket-proxy#4]
When trying to expose the entire grpc api in websockets, it would be a nice feature to support the request-response endpoints.

**Comment by johanbrandhorst** [comment]
These are supported already by the underlying grpc-gateway, what use case do you have where you must not use normal HTTP methods?

**Comment by tmc** [comment]
@nirshirion ping, can you elaborate on your use case here?

**Comment by tmc** [comment]
I can kind of squint and see some sort of consistency argument here but without a real use case I'm not going to entertain this further. Please feel free to re-open.
